version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Location of your GitHub Actions workflows
    schedule:
      interval: "weekly"

  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/" # Location of your package.json file
    schedule:
      interval: "weekly"